'use client';
import { Client, Account, TablesDB, Storage, ID, Query } from 'appwrite';
import type { Product } from './data';
const endpoint=process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT||'https://fra.cloud.appwrite.io/v1'; const projectId=process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID||'6ab043c3000e59fe64d7';
export const databaseId=process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID||'6ab14ce0000558baadff'; export const tableId=process.env.NEXT_PUBLIC_APPWRITE_PRODUCTS_TABLE_ID||process.env.NEXT_PUBLIC_APPWRITE_PRODUCTS_COLLECTION_ID||'6ab14d9700195368d864'; export const storageBucketId=process.env.NEXT_PUBLIC_APPWRITE_STORAGE_BUCKET_ID||'6ab161b800218bb2c2da'; export const appwriteReady=Boolean(endpoint&&projectId&&databaseId&&tableId);
export const client=new Client().setEndpoint(endpoint).setProject(projectId); export const account=new Account(client); export const tablesDB=new TablesDB(client); export const storage=new Storage(client);
export async function listProducts():Promise<Product[]>{if(!appwriteReady)return [];try{const r=await tablesDB.listRows({databaseId,tableId,queries:[Query.equal('status','Published'),Query.orderDesc('$createdAt')]});return r.rows as unknown as Product[]}catch{return []}}
export async function listAllProducts():Promise<Product[]>{if(!appwriteReady)throw new Error('Complete the Appwrite TablesDB database, Products table and storage bucket IDs before using the admin dashboard.');const r=await tablesDB.listRows({databaseId,tableId,queries:[Query.orderDesc('$createdAt')]});return r.rows as unknown as Product[]}
export async function createProduct(product:Product):Promise<Product>{if(!appwriteReady)throw new Error('Appwrite TablesDB is not configured yet. Add the database and table IDs.');return await tablesDB.createRow({databaseId,tableId,rowId:ID.unique(),data:product}) as unknown as Product}
export async function updateProduct(id:string,product:Partial<Product>):Promise<Product>{if(!appwriteReady)throw new Error('Appwrite TablesDB is not configured yet. Add the database and table IDs.');return await tablesDB.updateRow({databaseId,tableId,rowId:id,data:product}) as unknown as Product}
export async function deleteProduct(id:string){if(!appwriteReady)throw new Error('Appwrite TablesDB is not configured yet.');await tablesDB.deleteRow({databaseId,tableId,rowId:id})}
export async function uploadImage(file:File):Promise<string>{if(!appwriteReady||!storageBucketId)throw new Error('Add the Appwrite storage bucket ID before uploading images.');const uploaded=await storage.createFile(storageBucketId,ID.unique(),file);return storage.getFileView(storageBucketId,uploaded.$id).toString()}
